/**
 * Pull the icons this app uses out of Open Icons and write src/icons/glyphs.ts.
 *
 * The whole set is 172 icons; a single object literal is not tree-shakeable, so
 * carrying all of it would put ~800 KB of path data in the bundle to use 18 of
 * them. USED below is therefore the manifest: add a name to it, re-run, commit
 * the result. The generated file is committed on purpose — the build must not
 * depend on a sibling checkout being present.
 *
 *   node scripts/sync-icons.mjs [path-to-open-icons-playground]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const LIB = process.argv[2] ?? resolve(HERE, '../../open-icons-playground')

// Every icon the app renders, and where. Keep it alphabetical.
const USED = {
  check: 'ColorList copy confirmation, SwatchTray selected badge',
  'chevron-left': 'EditMode back',
  close: 'ColorList remove stop, SearchBar clear, GradientPage close',
  copy: 'ColorList copy hex',
  edit: 'GradientPage edit title',
  grid: 'Gallery layout — even grid',
  'grid-dense': 'Gallery layout — dense, no captions',
  'grid-masonry': 'Gallery layout — masonry',
  heart: 'Drawer empty state, HeartButton unliked',
  'heart-fill': 'HeartButton liked, LikeCountBadge',
  lock: 'ColorList locked, LockedColors summary',
  'lock-open': 'ColorList unlocked',
  'pause-fill': 'PlayButton playing',
  pin: 'ColorList position unpinned',
  'pin-fill': 'ColorList position pinned',
  'play-fill': 'PlayButton paused',
  search: 'SearchBar',
  share: 'BoardShare trigger',
  trash: 'DrumPicker remove drum',
}

const src = JSON.parse(readFileSync(resolve(LIB, 'icons/icons.json'), 'utf8'))

const missing = Object.keys(USED).filter((n) => !(n in src.icons))
if (missing.length) {
  console.error(`not in the set: ${missing.join(', ')}`)
  process.exit(1)
}

const rows = Object.entries(USED)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, where]) => {
    const key = /^[a-z][a-zA-Z0-9]*$/.test(name) ? name : `'${name}'`
    return `  // ${where}\n  ${key}:\n    ${JSON.stringify(src.icons[name])},`
  })
  .join('\n')

const out = `/**
 * GENERATED by scripts/sync-icons.mjs — do not edit by hand.
 *
 * Open Icons, ${src.grid}px grid, stroke ${src.stroke} — the axis weight this app's LDS
 * theme asks for (--icon-weight: 2). The geometry is weight-aware: clearances
 * are ratios of the stroke, so a different weight is a different drawing, not
 * the same paths at a different stroke-width. Do not retune stroke-width here.
 *
 * \\\${u} marks a mask or clip id. <Icon> swaps in a per-instance id so several
 * copies of one icon on a page cannot collide.
 */
export const GLYPHS = {
${rows}
} as const

export type IconName = keyof typeof GLYPHS
`

const dest = resolve(HERE, '../src/icons/glyphs.ts')
writeFileSync(dest, out)
console.log(`${Object.keys(USED).length} icons -> src/icons/glyphs.ts (${(out.length / 1024).toFixed(1)} KB)`)
